version: '3.8'

services:
  web:
    build: ./services/web
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - static_volume:/home/app/web/src/static
      - media_volume:/home/app/web/src/images
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./services/nginx
    volumes:
      - static_volume:/home/app/web/src/static
      - media_volume:/home/app/web/src/images
    ports:
      - 9000:80
    depends_on:
      - web
volumes:
  postgres_data_prod:
  static_volume:
  media_volume: