version: '3.8'

services:
  web:
    build: ./services/web
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - static_volume:/home/app/web/api/static
      - media_volume:/home/app/web/api/images
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    networks:
      finalyear-network:
        aliases:
          - backend
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    networks:
      finalyear-network:
        aliases:
          - db
  vue:
    build: ./services/frontend/finalyear-client
    volumes:
      - media_volume:/home/app/web/api/images
    networks:
      finalyear-network:
        aliases:
          - frontend
  nginx:
    build: ./services/nginx
    volumes:
      - static_volume:/home/app/web/api/static
      - media_volume:/home/app/web/api/images
    ports:
      - 9000:80
    depends_on:
      - web
      - vue
    networks:
      finalyear-network:
        aliases:
          - proxy
volumes:
  postgres_data_prod:
  static_volume:
  media_volume:

networks:
   finalyear-network: